version: '3'

volumes:
  keycloak_volume:
      driver: local
  redis:

networks:
  oidc_network:
    driver: bridge
    
  public_network:
    driver: bridge

services:

  public_proxy:
    build: ${public_proxy_build}
    container_name: ${public_proxy_name}
    hostname: ${public_proxy_name}
    ports:
      - ${port_public_proxy}:80
    networks:
    - public_network

  public_web:
    build: ${public_web_build}
    # コンテナ名
    container_name: ${public_web_name}
    hostname: ${public_web_name}
  
    # 環境変数を設定
    environment:
      - DEBUG=app:*
      - CHOKIDAR_USEPOLLING=true
    tty: true
    
    # ホスト側のポート:コンテナのポート
    ports:
      - '${port_public_web}:3000'

    # ソースコードを格納するフォルダをマウント
    #（ホスト側の./srcをコンテナの/appにマウント）
    volumes:
      - ${public_web_vlumes}:${public_web_working_dir}

    # 起動時のカレントフォルダを指定
    working_dir: ${public_web_working_dir}

    networks:
      - public_network

  oauth2_proxy:
    build: ${iap_build}
    container_name: ${iap_name}
    hostname: ${iap_name}
    ports:
      - ${port_iap}:${port_iap}

    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:${port_iap}
      OAUTH2_PROXY_PROVIDER: ${OAUTH2_PROXY_PROVIDER}
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_EMAIL_DOMAINS: ${OAUTH2_PROXY_EMAIL_DOMAINS}
      OAUTH2_PROXY_UPSTREAMS: ${OAUTH2_PROXY_UPSTREAMS}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_SESSION_STORE_TYPE: redis
      OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://redis/
      # 以下、HTTPS ではなく HTTP で動かすための設定
      OAUTH2_PROXY_COOKIE_SECURE: 'false'
      OAUTH2_PROXY_REDIRECT_URL: http://test_app:${port_public_proxy}/oauth2/callback
    
    networks:
    - public_network

  redis:
    image: redis
    volumes:
      - redis:/data
  
  # 以下 認証認可
  mysql:
    image: ${keycloak_data_image}
    # コンテナ名
    container_name: ${keycloak_data_name}

    volumes:
      - keycloak_volume:${keycloak_data_volume__container}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    networks:
      - oidc_network
        
  keycloak:
      image: ${keycloak_image}
      # コンテナ名
      container_name: ${keycloak_name}

      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: password
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - ${port_keycloak}:8080
      depends_on:
        - mysql
      networks:
        - oidc_network
